package gtm

import (
	"fmt"
	"html"
	"strings"
)

// Storefront generation — the portfolio index, generated from the same manifest
// that drives the per-product pages. Adding an app to the manifest updates the
// storefront automatically; planned apps render as muted "Coming soon" cards (no
// price, no fake checkout). Shares the landing design system (RootCSS seam) so
// the storefront matches the house palette.

// StorefrontModel is the full storefront page.
type StorefrontModel struct {
	Title     string
	Brand     string // footer attribution
	Badge     string // eyebrow chip
	Intro     string // tagline under the H1
	Note      string // closing note (provenance / pricing caveat)
	RootCSS   string // optional generated `:root{}` (house palette); empty => default theme
	Generated string // RFC3339 build stamp
	Groups    []StorefrontGroup
}

// StorefrontGroup is one labeled section of cards (e.g. "For teams · sales-led").
type StorefrontGroup struct {
	Heading string
	Cards   []StorefrontCard
}

// StorefrontCard is one product tile.
type StorefrontCard struct {
	Name     string
	Category string   // small mono eyebrow
	Desc     string   // one-paragraph pitch
	Price    string   // pre-formatted, e.g. "$28.5K" / "$39" (empty for planned)
	Period   string   // e.g. "/yr · Business anchor", "one-time · Pro"
	Href     string   // link to the product page (or its coming-soon stub)
	Planned  bool     // render muted + a "Coming soon" badge
	Stats    []string // pills, e.g. ["GO", "LTV:CAC 11.8×"]
}

// RenderStorefrontHTML emits the self-contained portfolio index. Every dynamic
// value is HTML-escaped.
func RenderStorefrontHTML(s *StorefrontModel) string {
	e := html.EscapeString
	var b strings.Builder
	w := func(str string) { b.WriteString(str) }
	wf := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	title := firstNonEmpty(strings.TrimSpace(s.Title), "Products")
	brand := firstNonEmpty(strings.TrimSpace(s.Brand), "nicos-tools")

	w("<!doctype html>\n")
	w("<!--\n  " + e(brand) + " — product storefront, generated by `ngtm landing --from`.\n")
	w("  Single-file, dependency-free. Add an app to the manifest, not by hand.\n-->\n")
	w("<html lang=\"en\">\n<head>\n")
	w("  <meta charset=\"utf-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n")
	wf("  <title>%s — %s</title>\n", e(brand), e(title))
	wf("  <meta name=\"description\" content=\"%s\" />\n", e(s.Intro))
	w(storefrontStyle(s.RootCSS))
	w("</head>\n<body>\n<div class=\"wrap\">\n\n")

	w("  <header class=\"hero\">\n")
	wf("    <span class=\"badge\">%s</span>\n", e(firstNonEmpty(s.Badge, brand+" · portfolio")))
	wf("    <h1>%s</h1>\n", e(title))
	if s.Intro != "" {
		wf("    <p class=\"tagline\">%s</p>\n", e(s.Intro))
	}
	w("  </header>\n\n")

	for _, g := range s.Groups {
		if len(g.Cards) == 0 {
			continue
		}
		wf("  <h2>%s</h2>\n", e(g.Heading))
		w("  <div class=\"product-grid\">\n")
		for _, c := range g.Cards {
			cls := "product"
			if c.Planned {
				cls = "product soon"
			}
			wf("    <div class=\"%s\">\n", cls)
			if c.Planned {
				w("      <span class=\"soon-badge\">Coming soon</span>\n")
			}
			if c.Category != "" {
				wf("      <span class=\"cat\">%s</span>\n", e(c.Category))
			}
			wf("      <h3><a href=\"%s\">%s</a></h3>\n", e(c.Href), e(c.Name))
			if c.Desc != "" {
				wf("      <p class=\"desc\">%s</p>\n", e(c.Desc))
			}
			if c.Price != "" {
				wf("      <div class=\"priceline\"><span class=\"amt\">%s</span>", e(c.Price))
				if c.Period != "" {
					wf("<span class=\"per\">%s</span>", e(c.Period))
				}
				w("</div>\n")
			}
			if len(c.Stats) > 0 {
				w("      <div class=\"stats\">")
				for i, st := range c.Stats {
					pill := "pill"
					if i == 0 && strings.EqualFold(strings.TrimSpace(st), "GO") {
						pill = "pill go"
					}
					wf("<span class=\"%s\">%s</span>", pill, e(st))
				}
				w("</div>\n")
			}
			btn, label := "btn btn-primary", "View "+c.Name+" →"
			if c.Planned {
				btn, label = "btn btn-ghost", "Preview →"
			}
			wf("      <a class=\"%s\" href=\"%s\">%s</a>\n", btn, e(c.Href), e(label))
			w("    </div>\n")
		}
		w("  </div>\n\n")
	}

	if s.Note != "" {
		wf("  <div class=\"note\">%s</div>\n\n", e(s.Note))
	}
	w("  <footer>\n")
	wf("    %s — product portfolio. Generated by <code>ngtm landing --from</code> on %s. Add an app to the manifest, not by hand.\n",
		e(brand), e(s.Generated))
	w("  </footer>\n\n")
	w("</div>\n</body>\n</html>\n")
	return b.String()
}

// storefrontStyle composes the storefront stylesheet, reusing the landing
// design-token seam (the generated house `:root{}` or the default theme).
func storefrontStyle(rootCSS string) string {
	root := strings.TrimSpace(rootCSS)
	if root == "" {
		root = defaultLandingRoot
	}
	return "  <style>\n" + root + "\n" + storefrontStyleBody + "  </style>\n"
}

const storefrontStyleBody = `    * { box-sizing: border-box; }
    body { margin: 0; background: var(--bg); color: var(--fg);
      font-family: var(--sans); line-height: 1.6; font-size: 16px; }
    .wrap { max-width: 1040px; margin: 0 auto; padding: 56px 24px 96px; }
    header.hero { border-bottom: 1px solid var(--border); padding-bottom: 32px; margin-bottom: 12px; }
    .badge { display: inline-block; font-family: var(--mono); font-size: 12px;
      color: var(--accent); border: 1px solid var(--border); border-radius: 999px;
      padding: 3px 12px; margin-bottom: 16px; }
    h1 { font-size: 42px; margin: 0 0 10px; letter-spacing: -0.6px; }
    .tagline { font-size: 19px; color: var(--muted); margin: 0; max-width: 70ch; }
    h2 { font-size: 16px; text-transform: uppercase; letter-spacing: 1px; color: var(--muted);
      font-family: var(--mono); margin: 44px 0 4px; font-weight: 600; }
    a { color: var(--accent2); text-decoration: none; }
    code { font-family: var(--mono); background: var(--code); padding: 1px 6px; border-radius: 5px; font-size: 0.86em; }
    .product-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 20px; margin: 18px 0; }
    .product { position: relative; display: flex; flex-direction: column; gap: 12px;
      background: var(--panel); border: 1px solid var(--border); border-radius: 16px; padding: 26px 26px 24px;
      transition: border-color .15s ease, transform .06s ease; }
    .product:hover { border-color: var(--accent2); transform: translateY(-2px); }
    .product.soon { opacity: 0.72; }
    .product.soon:hover { opacity: 1; }
    .soon-badge { position: absolute; top: -11px; left: 24px; background: var(--code); color: var(--muted);
      border: 1px solid var(--border); font-family: var(--mono); font-size: 11px; font-weight: 700;
      padding: 2px 10px; border-radius: 999px; }
    .product .cat { font-family: var(--mono); font-size: 12px; color: var(--muted); }
    .product h3 { font-size: 24px; margin: 0; letter-spacing: -0.3px; }
    .product h3 a { color: var(--fg); }
    .product h3 a:hover { color: var(--accent2); }
    .product .desc { color: var(--muted); font-size: 15px; margin: 0; flex: 1; }
    .priceline { display: flex; align-items: baseline; gap: 8px; margin-top: 4px; }
    .priceline .amt { font-size: 26px; font-weight: 700; letter-spacing: -0.5px; }
    .priceline .per { font-size: 13px; color: var(--muted); font-family: var(--mono); }
    .stats { display: flex; flex-wrap: wrap; gap: 8px; }
    .pill { font-family: var(--mono); font-size: 11px; padding: 2px 9px; border-radius: 999px;
      border: 1px solid var(--border); color: var(--muted); }
    .pill.go { color: var(--accent); border-color: var(--accent); }
    .btn { display: inline-block; text-align: center; font-family: var(--sans); font-size: 14.5px;
      font-weight: 600; padding: 10px 20px; border-radius: 10px; border: 1px solid var(--border);
      margin-top: 4px; transition: transform .05s ease, border-color .15s ease; }
    .btn:active { transform: translateY(1px); }
    .btn-primary { background: var(--accent); color: var(--accent-fg, #07140a); border-color: var(--accent); }
    .btn-primary:hover { filter: brightness(1.06); }
    .btn-ghost { background: transparent; color: var(--fg); }
    .btn-ghost:hover { border-color: var(--accent2); color: var(--accent2); }
    .note { border-left: 3px solid var(--accent); background: var(--code);
      padding: 12px 16px; border-radius: 0 8px 8px 0; margin: 28px 0 0; color: var(--muted); font-size: 14px; }
    footer { margin-top: 56px; padding-top: 20px; border-top: 1px solid var(--border);
      color: var(--muted); font-size: 13px; }
`
